name: MHAMinecraft
version: 1.0
main: devtenko.mhaminecraft.MHAMinecraft
api-version: 1.13
authors: [DevTenko]
commands:
  start:
    usage: "Usage: /start"
    description: Starts game only for OP
  switch:
    usage: "Usage: /switch [decay|overhaul|gravity|hell_flame|comrpess|erasure|warp|hardening|permeation]"
    description: Works for all players before game start